name: pr
on:
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          # We want the latest 1.17, since that's what we're developing with
          go-version: '<1.18'
      - run: |
          make test
